# Generated by Django 4.2.23 on 2025-06-12 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_content', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(verbose_name=datetime.datetime(2025, 6, 12, 16, 57, 5, 763986, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
