# Generated by Django 4.2.23 on 2025-06-12 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanlog',
            old_name='recipient_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 17, 10, 31, 57644, tzinfo=datetime.timezone.utc)),
        ),
    ]
