# Generated by Django 4.2.23 on 2025-06-12 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_api', '0002_rename_recipient_email_scanlog_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 17, 52, 6, 634059, tzinfo=datetime.timezone.utc)),
        ),
    ]
