# Generated by Django 4.2.23 on 2025-06-12 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_api', '0003_alter_scanlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 17, 54, 51, 553291, tzinfo=datetime.timezone.utc)),
        ),
    ]
