# Generated by Django 4.2.23 on 2025-06-12 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_api', '0004_alter_scanlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
