# Generated by Django 4.2.23 on 2025-06-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_api', '0005_alter_scanlog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanlog',
            old_name='email',
            new_name='to_email',
        ),
    ]
