# Generated by Django 4.2.23 on 2025-06-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
